In [2]:
import numpy as np
import pandas as pd

In [8]:
gallup = pd.read_csv("data/USAIPO1936-0053.csv")
gallup.T

,0,1,2,3,4,5,6,7,8,9,...,5505,5506,5507,5508,5509,5510,5511,5512,5513,5514
form,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state,Indiana,Illinois,Michigan,Virginia,Florida,Florida,Georgia,Georgia,North Carolina,Alabama,...,Virginia,Minnesota,Tennessee,Texas,Mississippi,Mississippi,Indiana,Illinois,Michigan,Ohio
region,East Central,East Central,East Central,South and Southwest,South and Southwest,South and Southwest,South and Southwest,South and Southwest,South and Southwest,South and Southwest,...,South and Southwest,West Central,South and Southwest,South and Southwest,South and Southwest,South and Southwest,East Central,East Central,East Central,East Central
female,Male,Male,Male,Male,Male,Male,Male,Male,Male,Male,...,Male,Male,Male,Male,Male,Male,Male,Male,Female,Male
age,NaN,NaN,NaN,55 yrs and over,55 yrs and over,55 yrs and over,55 yrs and over,55 yrs and over,55 yrs and over,55 yrs and over,...,45-54 yrs,35-44 yrs,35-44 yrs,55 yrs and over,55 yrs and over,55 yrs and over,25-34 yrs,25-34 yrs,35-44 yrs,55 yrs and over
class,Av+,Av+,Av,P or P+,Av+,Av+,Av+,Av+,Av,P or P+,...,P or P+,Av,NaN,Av,Av+,Av+,Av+,Av,Av,Av+
OCCUPATION1,Skilled workers,Skilled workers,Business,Skilled workers,Skilled workers,Business,Other and None,Skilled workers,Business,Skilled workers,...,Skilled workers,Business,Business,Skilled workers,Other and None,Skilled workers,Skilled workers,Professiol,Professiol,Skilled workers
OCCUPATION2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OCCUPATION3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
black,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
size,Urban,Urban,Urban,Urban,Small town,Small town,Small town,Farm,Urban,Urban,...,Urban,Urban,Urban,Urban,Farm,Farm,Farm,Urban,Urban,Small town
education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGE_3WAY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGE40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OCC8,Labor,Labor,Professional,Labor,Labor,Professional,Other,Labor,Professional,Labor,...,Labor,Professional,Professional,Labor,Other,Labor,Labor,Professional,Professional,Labor
prof,Not Professional,Not Professional,Professional,Not Professional,Not Professional,Professional,Not Professional,Not Professional,Professional,Not Professional,...,Not Professional,Professional,Professional,Not Professional,Not Professional,Not Professional,Not Professional,Professional,Professional,Not Professional
REGION4,Midwest,Midwest,Midwest,South,South,South,South,South,South,South,...,South,Midwest,South,South,South,South,Midwest,Midwest,Midwest,Midwest
EDU_RECODE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VOTE_PRO,Landon,Landon,Landon,fdr,fdr,fdr,fdr,fdr,fdr,fdr,...,fdr,fdr,fdr,fdr,fdr,fdr,Landon,Landon,Landon,Landon
VOTE_RETRO,Hoover,Hoover,Hoover,fdr,fdr,fdr,fdr,fdr,fdr,fdr,...,Did not vote,fdr,fdr,fdr,fdr,fdr,Hoover,Hoover,Hoover,Hoover
PHONE_RECODE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CAR_RECODE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ballot,53,53,53,53,53,53,53,53,53,53,...,53,53,53,53,53,53,53,53,53,53
Q1,Yes,Yes,No,Yes,Yes,No,Yes,Yes,No,No,...,Yes,NaN,Yes,Yes,No,Yes,No,No,Yes,Yes
Q2,Yes,NaN,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes
Q3,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes
Q4A,Roosevelt,Landon,Landon,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,...,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Landon,Roosevelt,Roosevelt,NaN
Q4B,Roosevelt,Landon,Landon,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,...,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Landon,Roosevelt,Landon,Landon
Q4C,Landon,Landon,Landon,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,...,Roosevelt,Landon,NaN,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Landon,Landon,Neither
Q5A,Landon,Landon,Landon,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,...,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Roosevelt,Landon,Landon,Landon,Landon
Q5B,"Yes, voted for Hoover","Yes, voted for Hoover","Yes, voted for Hoover","Yes, voted for Roosevelt","Yes, voted for Roosevelt","Yes, voted for Roosevelt","Yes, voted for Roosevelt","Yes, voted for Roosevelt","Yes, voted for Roosevelt","Yes, voted for Roosevelt",...,No,"Yes, voted for Roosevelt","Yes, voted for Roosevelt","Yes, voted for Roosevelt","Yes, voted for Roosevelt","Yes, voted for Roosevelt","Yes, voted for Hoover","Yes, voted for Hoover","Yes, voted for Hoover","Yes, voted for Hoover"
farm,Non-Farm,Non-Farm,Non-Farm,Non-Farm,Non-Farm,Non-Farm,Non-Farm,Farm,Non-Farm,Non-Farm,...,Non-Farm,Non-Farm,Non-Farm,Non-Farm,Farm,Farm,Farm,Non-Farm,Non-Farm,Non-Farm
SIZE3,Urban,Urban,Urban,Urban,Rural Non-Farm,Rural Non-Farm,Rural Non-Farm,Farm,Urban,Urban,...,Urban,Urban,Urban,Urban,Farm,Farm,Farm,Urban,Urban,Rural Non-Farm
urban,Urban,Urban,Urban,Urban,Non-Urban,Non-Urban,Non-Urban,Non-Urban,Urban,Urban,...,Urban,Urban,Urban,Urban,Non-Urban,Non-Urban,Non-Urban,Urban,Urban,Non-Urban
StPOAbrv,in,il,mi,va,fl,fl,ga,ga,nc,al,...,va,mn,tn,tx,ms,ms,in,il,mi,oh
SOUTH11,Non-South,Non-South,Non-South,South,South,South,South,South,South,South,...,South,Non-South,South,South,South,South,Non-South,Non-South,Non-South,Non-South
SOUTH11xBLACK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SOUTH12,Non-South,Non-South,Non-South,South,South,South,South,South,South,South,...,South,Non-South,South,South,South,South,Non-South,Non-South,Non-South,Non-South
SOUTH12xBLACK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
south,Non-South,Non-South,Non-South,South,South,South,South,South,South,South,...,South,Non-South,South,South,South,South,Non-South,Non-South,Non-South,Non-South
SOUTHxBLACK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,1936,1936,1936,1936,1936,1936,1936,1936,1936,1936,...,1936,1936,1936,1936,1936,1936,1936,1936,1936,1936
WtPubFeas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WtVotFeas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
pd.crosstab(gallup["Q5A"], gallup["Q3"])

Q3            No   Yes
Q5A
Landon       921   820
Lemke         41   109
Other party    6     6
Roosevelt    442  2048
Thomas        10    41

In [15]:
kff = pd.read_csv("data/31125187.csv")

pd.set_option('display.max_rows', 146)
kff.T

                                                                0     \
id                                                                 2
STATUS                                                      complete
INTERVIEW_START                                            4/16/2026
intvwdate                                                  4/16/2026
XCHANNEL                                                        CAWI
EVERINBOUND
S1
D1
STATE1                                                    New Mexico
STATEEXPMEDI                                                     Yes
GVNREXPMEDI                             Yes - Democratic/Independent
STATEGVNR                                        Democratic governor
STATE2024VOTE                                Voted for Kamala Harris
QUOTAGROUP                                                    PP Web
age                                                               71
AGE2
AGETOT                                                         70-74
recage                                                           65+
recage2                                                          65+
recage3                                                          65+
recage4                                                        70-74
recage5                                                          65+
recage6                                                          50+
Q1_A                                                 Not too worried
Q1_B                                                 Not too worried
Q1_C                                                 Not too worried
Q1_D                                                Somewhat worried
Q1_E                                                    Very worried
COVERAGE                                 Covered by health insurance
COVTYPE            Medicare, the government program for adults 65...
agecov
agecovtype
Q2                 Eliminating prior authorization, where health ...
Q3_A                                                         Neither
Q3_B                                                   The Democrats
Q3_C                                                   The Democrats
Q3_D                                                   The Democrats
Q3_E                                                   The Democrats
Q3_F                                                         Neither
Q4_A                                             Strongly disapprove
Q4_B                                             Somewhat disapprove
Q4_C                                             Somewhat disapprove
Q4_D                                             Strongly disapprove
Q4_E                                             Strongly disapprove
Q14                                              Strongly disapprove
RVOTE                                                            Yes
Q5_A                                                    Major impact
Q5_B                                                    Minor impact
Q5_C                                                    Major impact
Q6_A                                                    Major impact
Q6_B                                                    Minor impact
Q6_C                                                    Major impact
Q7                     They have a plan to address health care costs
Q16                                           About the right amount
Q17
Q18                                            Not enough regulation
Q19                   Would still say there is not enough regulation
Q23_A                                                     Not at all
Q23_B                                                  A fair amount
Q23_C                                                       Not much
Q23_D                                                     Not at all
Q15_A                                                    None at all
Q15_B                                                    None at all
Q15_C                                                       A little
Q20                                      Major role, but not leading
Q21                                                       Major cuts
Q22_A                                                      No impact
Q22_B                                                Negative impact
Q22_C                                                Negative impact
Q22_D                                                Negative impact
EVOTE                           About the same as previous elections
PVOTE                                                       Democrat
PARTY                                                    Independent
PARTYLEAN                                                 Democratic
party3                                       Democrat/Indep lean Dem
party5                                          Independent lean Dem
MAGA1
MAHA1                                                             No
Q10_1_OTHER_code1
Q9
Q11_A
Q11_B
Q11_C
Q11_D
Q11_E
Q11_NUM
Q12
TOP_PRIORITY
Q13
RGENDER                                                        Woman
GENDER                                                        FEMALE
gendervar                                                     Female
LGBQ                                        Straight or heterosexual
LGBT_TOT                                                    NON-LGBT
EDUC               High school graduate (Grade 12 with diploma or...
receduc                                         High school graduate
receduc2                                         High school or less
receduc3                                           Less than college
receduc4                                         HIGH SCHOOL OR LESS
HISPANIC                                                          No
race_1                                                         White
race_2                                 NOT Black or African-American
race_3                                                     NOT Asian
race_4                                           NOT American Indian
race_6                                             NOT Alaska Native
race_8                                            NOT Multiple Races
race_98                                               NOT Don't know
race_99                                                  NOT REFUSED
race_100                                               NOT Web Blank
RACENUM                                                            1
NATIVITY                                                        U.S.
racethn                                                        WHITE
racethn2                                         White, non-Hispanic
CHILD                                                             No
INT5                                             Several times a day
CE1
CE2
CIVICENGAGE                                                        1
hhadults                                                           2
PPD                                                               No
state
INCOME                                  $40,000 to less than $50,000
recincome                                                $40K-$89.9K
recincome2                                                    $40K +
recincome3                                            Less than $90K
RECINCOME4                                           Less than $100k
length                                                           752
BIDENT1
BIDENT2
BIDENT3
BIDENT4
BIDENT5
sample                                                           Web
USERDATA                                              Prob panel Web
CREGION                                                         West
cstate                                                    New Mexico
density                                                       Lowest
USR_NEW                                                        Rural
lang                                                         English
Division                                                    Mountain
changesex                                              sex = rgender
WAIVER                                                             2
WEIGHT_PID_ADJ                                                1.1448
MAGA_PARTY3                                             Dem/lean Dem
MAHA1_REC                                         Not MAHA supporter
RACE_other

                                                                1     \
id                                                                 4
STATUS                                                      complete
INTERVIEW_START                                            4/15/2026
intvwdate                                                  4/15/2026
XCHANNEL                                                        CAWI
EVERINBOUND
S1
D1
STATE1                                                South Carolina
STATEEXPMEDI                                                No/Maybe
GVNREXPMEDI                                                 No/Maybe
STATEGVNR                                        Republican governor
STATE2024VOTE                                 Voted for Donald Trump
QUOTAGROUP                                                    PP Web
age                                                               74
AGE2
AGETOT                                                         70-74
recage                                                           65+
recage2                                                          65+
recage3                                                          65+
recage4                                                        70-74
recage5                                                          65+
recage6                                                          50+
Q1_A                                              Not at all worried
Q1_B                                              Not at all worried
Q1_C                                              Not at all worried
Q1_D                                              Not at all worried
Q1_E                                              Not at all worried
COVERAGE                                 Covered by health insurance
COVTYPE            Medicare, the government program for adults 65...
agecov
agecovtype
Q2                         Paying less out-of-pocket for health care
Q3_A                                                 The Republicans
Q3_B                                                 The Republicans
Q3_C                                                 The Republicans
Q3_D                                                 The Republicans
Q3_E                                                 The Republicans
Q3_F                                                 The Republicans
Q4_A                                                Somewhat approve
Q4_B                                                Somewhat approve
Q4_C                                                Somewhat approve
Q4_D                                                Somewhat approve
Q4_E                                                Somewhat approve
Q14                                                 Somewhat approve
RVOTE                                                            Yes
Q5_A                                                No impact at all
Q5_B                                                No impact at all
Q5_C                                                    Minor impact
Q6_A                                                No impact at all
Q6_B                                                No impact at all
Q6_C                                                    Minor impact
Q7                 They are willing to take on health insurance a...
Q16                                            Not enough regulation
Q17                                             Would change my view
Q18                                           About the right amount
Q19
Q23_A                                                       Not much
Q23_B                                                       Not much
Q23_C                                                  A fair amount
Q23_D                                                       Not much
Q15_A                                                           Some
Q15_B                                                           Some
Q15_C                                                           Some
Q20                                                       Minor role
Q21                                                       Minor cuts
Q22_A                                                      No impact
Q22_B                                                      No impact
Q22_C                                                      No impact
Q22_D                                                      No impact
EVOTE                           About the same as previous elections
PVOTE                                                     Republican
PARTY                                                    Independent
PARTYLEAN                                              Neither/Other
party3                                             Pure Independents
party5                                        Independent/Don't lean
MAGA1
MAHA1                                                            Yes
Q10_1_OTHER_code1                         Vaccine and Medical Choice
Q9                                                  Somewhat support
Q11_A                              Important, but not a top priority
Q11_B                                                 A top priority
Q11_C                                                 A top priority
Q11_D                                                 A top priority
Q11_E                              Important, but not a top priority
Q11_NUM                                                            3
Q12                 Limiting corporate influence on U.S. food policy
TOP_PRIORITY        Limiting corporate influence on U.S. food policy
Q13
RGENDER                                                        Woman
GENDER                                                        FEMALE
gendervar                                                     Female
LGBQ                                        Straight or heterosexual
LGBT_TOT                                                    NON-LGBT
EDUC               Post-graduate or professional degree, includin...
receduc                                                    College +
receduc2                                                   College +
receduc3                                                   College +
receduc4                                              SOME COLLEGE +
HISPANIC                                                          No
race_1                                                         White
race_2                                 NOT Black or African-American
race_3                                                     NOT Asian
race_4                                           NOT American Indian
race_6                                             NOT Alaska Native
race_8                                            NOT Multiple Races
race_98                                               NOT Don't know
race_99                                                  NOT REFUSED
race_100                                               NOT Web Blank
RACENUM                                                            1
NATIVITY                                                        U.S.
racethn                                                        WHITE
racethn2                                         White, non-Hispanic
CHILD                                                             No
INT5                                               Almost constantly
CE1
CE2
CIVICENGAGE                                                        1
hhadults                                                           2
PPD                                                               No
state
INCOME                                $100,000 to less than $200,000
recincome                                                      $90K+
recincome2                                                    $40K +
recincome3                                                    $90K +
RECINCOME4                                                    $100k+
length                                                           424
BIDENT1
BIDENT2
BIDENT3
BIDENT4
BIDENT5
sample                                                           Web
USERDATA                                              Prob panel Web
CREGION                                                        South
cstate                                                South Carolina
density                                                            2
USR_NEW                                                     Suburban
lang                                                         English
Division                                              South Atlantic
changesex                                              sex = rgender
WAIVER                                                             2
WEIGHT_PID_ADJ                                                1.5308
MAGA_PARTY3                                         Pure independent
MAHA1_REC                                        Weak MAHA supporter
RACE_other

                                                                2     \
id                                                                 6
STATUS                                                      complete
INTERVIEW_START                                            4/14/2026
intvwdate                                                  4/14/2026
XCHANNEL                                                        CAWI
EVERINBOUND
S1
D1
STATE1                                                 Massachusetts
STATEEXPMEDI                                                     Yes
GVNREXPMEDI                             Yes - Democratic/Independent
STATEGVNR                                        Democratic governor
STATE2024VOTE                                Voted for Kamala Harris
QUOTAGROUP                                                    PP Web
age                                                               54
AGE2
AGETOT                                                         50-54
recage                                                         18-64
recage2                                                        50-64
recage3                                                        45-54
recage4                                                        40-59
recage5                                                        45-64
recage6                                                          50+
Q1_A                                                 Not too worried
Q1_B                                                 Not too worried
Q1_C                                                 Not too worried
Q1_D                                                 Not too worried
Q1_E                                                 Not too worried
COVERAGE                                 Covered by health insurance
COVTYPE                     Plan (you/I) purchased (yourself/myself)
agecov                                          Insured Less than 65
agecovtype                                       Self-purchased plan
Q2                         Paying less out-of-pocket for health care
Q3_A                                                 The Republicans
Q3_B                                                 The Republicans
Q3_C                                                 The Republicans
Q3_D                                                    Both equally
Q3_E                                                 The Republicans
Q3_F                                                 The Republicans

In [19]:
kff["Q1_A"].value_counts()

Q1_A
Somewhat worried      390
Very worried          335
Not at all worried    310
Not too worried       308
Name: count, dtype: int64

In [20]:
kff["Q1_B"].value_counts()

Q1_B
Somewhat worried      468
Very worried          429
Not too worried       263
Not at all worried    183
Name: count, dtype: int64

In [21]:
kff["Q1_C"].value_counts()

Q1_C
Somewhat worried      454
Very worried          361
Not too worried       312
Not at all worried    215
Refused                 1
Name: count, dtype: int64

In [22]:
kff["Q1_D"].value_counts()

Q1_D
Somewhat worried      446
Not too worried       343
Very worried          332
Not at all worried    222
Name: count, dtype: int64

In [26]:
widths = [
    4, 3, 1, 1, 1, 3, 2, 2,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1,
    1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1,
    2, 2, 2, 2, 2, 2, 2,
    1, 1, 3,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    3,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1,
    3, 3, 3, 3, 3,
    3,
    3, 3, 3, 3, 3, 3,
    3, 3,
    1,
    3, 3,
    1, 1, 1, 1,
    1, 1, 1, 1, 1,
    2, 2, 2, 2,
    1, 1, 1, 1, 1, 1, 1, 1,
    2, 2, 2, 2,
    2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1
]

USIA = pd.read_fwf("data/i20068.dat", widths=widths, header=None)
USIA.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,...,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,...,2170,2171,2172,2173,2174,2175,2176,2177,2178,2179,2180,2181,2182,2183,2184,2185,2186,2187,2188,2189,2190,2191,2192,2193,2194,2195,2196,2197,2198,2199,2200,2201,2202,2203,2204,2205,2206,2207,2208,2209,2210,2221,2222,2223,2224,2225,2226,2227,2228,2229,2230,2231,2232,2233,2234,2235,2236,2237,2238,2239,2240,2241,2242,2243,2244,2245,2246,2247,2248,2249,2250,2251,
1,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,...,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,97.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,283.0,255.0,NaN
2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN
4,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,8.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,9.0,2.0,8.0,1.0,1.0,9.0,1.0,9.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,8.0,8.0,2.0,1.0,1.0,8.0,2.0,2.0,8.0,8.0,8.0,2.0,2.0,2.0,9.0,8.0,2.0,8.0,2.0,8.0,2.0,8.0,2.0,2.0,2.0,2.0,2.0,8.0,1.0,9.0,2.0,8.0,2.0,9.0,2.0,8.0,9.0,2.0,NaN
5,108.0,120.0,102.0,129.0,1.0,120.0,121.0,129.0,98.0,135.0,NaN,59.0,12.0,59.0,101.0,112.0,12.0,174.0,16.0,1.0,108.0,138.0,9.0,108.0,121.0,114.0,102.0,104.0,127.0,112.0,125.0,104.0,6.0,104.0,23.0,104.0,22.0,124.0,126.0,16.0,144.0,104.0,144.0,144.0,144.0,5.0,144.0,144.0,104.0,142.0,208.0,101.0,211.0,109.0,211.0,211.0,109.0,114.0,98.0,105.0,101.0,102.0,NaN,147.0,NaN,16.0,10.0,NaN,1.0,NaN,139.0,102.0,146.0,...,120.0,129.0,120.0,117.0,101.0,112.0,101.0,103.0,116.0,112.0,101.0,6.0,126.0,133.0,9.0,113.0,17.0,112.0,101.0,112.0,102.0,102.0,50.0,121.0,138.0,102.0,57.0,1.0,118.0,101.0,98.0,1.0,105.0,101.0,NaN,NaN,102.0,1.0,16.0,NaN,102.0,101.0,NaN,NaN,NaN,108.0,102.0,101.0,NaN,NaN,109.0,NaN,101.0,NaN,101.0,NaN,101.0,118.0,101.0,118.0,101.0,NaN,16.0,NaN,101.0,NaN,101.0,NaN,102.0,NaN,NaN,163.0,NaN
6,12.0,9.0,14.0,9.0,13.0,12.0,3.0,12.0,10.0,12.0,13.0,13.0,3.0,3.0,7.0,13.0,13.0,9.0,13.0,13.0,13.0,13.0,13.0,13.0,9.0,13.0,13.0,13.0,2.0,13.0,3.0,13.0,12.0,14.0,14.0,13.0,13.0,13.0,13.0,14.0,98.0,13.0,14.0,12.0,13.0,13.0,4.0,13.0,13.0,13.0,13.0,9.0,12.0,12.0,9.0,6.0,8.0,13.0,9.0,12.0,12.0,2.0,9.0,4.0,2.0,2.0,6.0,9.0,13.0,9.0,9.0,13.0,13.0,...,13.0,9.0,9.0,6.0,13.0,13.0,2.0,9.0,9.0,4.0,7.0,9.0,4.0,2.0,7.0,13.0,9.0,13.0,13.0,9.0,13.0,4.0,9.0,13.0,4.0,4.0,4.0,4.0,4.0,13.0,4.0,1.0,2.0,7.0,9.0,2.0,9.0,9.0,9.0,3.0,2.0,13.0,10.0,2.0,13.0,2.0,1.0,2.0,2.0,2.0,9.0,2.0,3.0,6.0,12.0,13.0,13.0,13.0,13.0,9.0,13.0,98.0,99.0,99.0,99.0,12.0,13.0,9.0,6.0,98.0,98.0,9.0,NaN
7,14.0,13.0,NaN,13.0,9.0,9.0,9.0,13.0,3.0,13.0,9.0,6.0,9.0,13.0,13.0,7.0,2.0,13.0,12.0,12.0,4.0,6.0,12.0,10.0,13.0,12.0,12.0,12.0,9.0,12.0,13.0,12.0,13.0,NaN,NaN,12.0,12.0,4.0,12.0,NaN,NaN,3.0,NaN,9.0,12.0,14.0,13.0,4.0,12.0,12.0,8.0,6.0,10.0,8.0,8.0,12.0,7.0,6.0,13.0,13.0,2.0,9.0,12.0,9.0,13.0,13.0,13.0,13.0,3.0,2.0,7.0,4.0,9.0,...,3.0,3.0,4.0,9.0,9.0,12.0,4.0,7.0,13.0,12.0,13.0,2.0,2.0,3.0,8.0,9.0,12.0,6.0,9.0,8.0,9.0,8.0,13.0,12.0,7.0,6.0,3.0,6.0,8.0,2.0,6.0,13.0,13.0,13.0,13.0,13.0,13.0,13.0,13.0,13.0,13.0,1.0,1.0,98.0,9.0,12.0,7.0,10.0,13.0,3.0,13.0,6.0,13.0,13.0,13.0,9.0,10.0,12.0,1.0,3.0,3.0,NaN,NaN,NaN,NaN,2.0,2.0,13.0,11.0,NaN,NaN,6.0,NaN
8,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,3.0,4.0,3.0,3.0,3.0,2.0,1.0,3.0,3.0,2.0,2.0,3.0,1.0,2.0,8.0,3.0,2.0,2.0,2.0,3.0,4.0,3.0,3.0,4.0,2.0,4.0,2.0,4.0,4.0,4.0,2.0,4.0,4.0,3.0,4.0,2.0,4.0,1.0,4.0,2.0,2.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,3.0,2.0,2.0,3.0,2.0,2.0,3.0,3.0,2.0,3.0,2.0,1.0,1.0,2.0,...,1.0,1.0,1.0,1.0,3.0,1.0,2.0,3.0,2.0,1.0,2.0,3.0,1.0,3.0,2.0,2.0,8.0,3.0,1.0,2.0,3.0,2.0,3.0,8.0,2.0,3.0,3.0,3.0,4.0,2.0,4.0,4.0,2.0,8.0,2.0,4.0,2.0,4.0,3.0,4.0,2.0,3.0,4.0,4.0,3.0,3.0,4.0,3.0,8.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,8.0,9.0,9.0,2.0,8.0,1.0,2.0,2.0,8.0,3.0,3.0,NaN
9,3.0,1.0,2.0,3.0,2.0,2.0,3.0,1.0,3.0,3.0,3.0,4.0,4.0,4.0,4.0,4.0,3.0,2.0,4.0,3.0,3.0,4.0,4.0,1.0,4.0,3.0,4.0,2.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,4.0,4.0,4.0,2.0,4.0,4.0,3.0,4.0,2.0,4.0,1.0,4.0,2.0,3.0,2.0,2.0,2.0,4.0,2.0,2.0,3.0,3.0,3.0,4.0,4.0,3.0,3.0,4.0,4.0,3.0,4.0,3.0,1.0,2.0,2.0,...,1.0,2.0,3.0,1.0,4.0,4.0,3.0,4.0,3.0,1.0,4.0,4.0,2.0,3.0,3.0,2.0,3.0,4.0,1.0,3.0,4.0,3.0,3.0,4.0,2.0,3.0,3.0,3.0,4.0,1.0,4.0,4.0,4.0,3.0,3.0,4.0,2.0,4.0,4.0,4.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,2.0,3.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,8.0,9.0,9.0,2.0,8.0,1.0,2.0,2.0,8.0,3.0,4.0,NaN
10,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,4.0,3.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,3.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,2.0,1.0,2.0,3.0,8.0,1.0,1.0,2.0,2.0,2.0,9.0,1.0,1.0,2.0,2.0,3.0,4.0,2.0,4.0,1.0,1.0,2.0,2.0,1.0,3.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,8.0,9.0,8.0,1.0,8.0,1.0,2.0,2.0,8.0,3.0,3.0,NaN
11,3.0,1.0,2.0,2.0,3.0,1.0,2.0,3.0,2.0,3.0,2.0,3.0,4.0,3.0,2.0,3.0,3.0,2.0,3.0,2.0,3.0,4.0,3.0,1.0,3.0,2.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0,4.0,2.0,3.0,3.0,2.0,3.0,2.0,3.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,4.0,1.0,1.0,1.0,...,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,3.0,8.0,2.0,2.0,3.0,1.0,3.0,2.0,3.0,8.0,1.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0,2.0,3.0,3.0,2.0,4.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,3.0,2.0,1.0,2.0,3.0,3.0,2.0,8.0,9.0,8.0,1.0,8.0,1.0,2.0,2.0,8.0,3.0,3.0,NaN
12,1.0,1.0,1.0,2.0,3.0,2.0,2.0,1.0,1.0,8.0,2.0,3.0,4.0,3.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,8.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,1.0,1.0,2.0,3.0,2.0,1.0,1.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,8.0,1.0,2.0,3.0,3.0,2.0,2.0,2.0,1.0,2.0,3.0,3.0,3.0,2.0,3.0,3.0,1.0,2.0,3.0,3.0,1.0,1.0,1.0,...,1.0,1.0,1.0,2.0,1.0,2.0,3.0,1.0,1.0,3.0,3.0,2.0,3.0,2.0,1.0,2.0,3.0,8.0,1.0,2.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,2.0,3.0,4.0,3.0,4.0,2.0,3.0,3.0,2.0,3.0,3.0,3.0,1.0,2.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,1.0,3.0,1.0,3.0,2.0,1.0,2.0,3.0,3.0,2.0,8.0,9.0,8.0,2.0,8.0,1.0,2.0,1.0,8.0,3.0,3.0,NaN
13,3.0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,1.0,1.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,4.0,2.0,1.0,3.0,3.0,3.0,1.0,1.0,4.0,3.0,3.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,3.0,3.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,3.0,2.0,3.0,2.0,2.0,3.0,3.0,2.0,3.0,4.0,1.0,1.0,1.0,...,3.0,1.0,3.0,1.0,1.0,2.0,2.0,1.0,4.0,3.0,3.0,2.0,1.0,3.0,1.0,1.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,9.0,3.0,2.0,3.0,2.0,2.0,2.0,2.0,4.0,2.0,1.0,2.0,3.0,4.0,3.0,3.0,1.0,4.0,8.0,8.0,2.0,8.0,8.0,8.0,2.0,2.0,8.0,8.0,2.0,3.0,8.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,8.0,9.0,8.0,8.0,8.0,1.0,2.0,1.0,8.0,3.0,4.0,NaN
14,1.0,1.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,3.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,1.0,...,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,3.0,2.0,2.0,1.0,3.0,1.0,1.0,2.0,3.0,3.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,1.0,2.0,8.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,8.0,9.0,8.0,1.0,8.0,1.0,2.0,1.0,8.0,3.0,2.0,NaN
15,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,8.0,1.0,2.0,2.0,1.0,2.0,3.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,1.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,2.0,3.0,1.0,3.0,3.0,3.0,1.0,1.0,2.0,...,2.0,1.0,1.0,3.0,1.0,2.0,3.0,1.0,1.0,2.0,2.0,2.0,3.0,3.0,1.0,2.0,3.0,3.0,1.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,1.0,2.0,2.0,3.0,2.0,3.0,8.0,2.0,2.0,8.0,2.0,2.0,8.0,8.0,8.0,8.0,8.0,8.0,1.0,3.0,8.0,3.0,2.0,8.0,2.0,3.0,3.0,3.0,8.0,9.0,8.0,1.0,8.0,1.0,2.0,1.0,8.0,3.0,2.0,NaN
16,2.0,1.0,2.0,2.0,2.0,2.0,2.0,4.0,1.0,3.0,2.0,3.0,4.0,3.0,3.0,4.0,4.0,1.0,1.0,2.0,3.0,3.0,3.0,1.0,2.0,3.0,1.0,3.0,2.0,1.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,3.0,1.0,2.0,2.0,2.0,3.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,2.0,3.0,1.0,1.0,2.0,...,3.0,1.0,3.0,3.0,1.0,3.0,3.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,1.0,3.0,3.0,4.0,4.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,4.0,3.0,3.0,4.0,3.0,3.0,3.0,2.0,2.0,3.0,8.0,3.0,2.0,8.0,2.0,3.0,3.0,3.0,8.0,9.0,8.0,2.0,8.0,1.0,2.0,1.0,8.0,3.0,3.0,NaN
17,4.0,4.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,1.0,1.0,8.0,1.0,2.0,1.0,3.0,2.0,8.0,2.0,8.0,8.0,2.0,1.0,1.0,3.0,2.0,4.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,2.0,2.0,3.0,2.0,2.0,1.0,1.0,8.0,2.0,2.0,2.0,3.0,2.0,3.0,3.0,3.0,2.0,1.0,8.0,2.0,2.0,2.0,8.0,3.0,2.0,9.0,8.0,1.0,1.0,1.0,...,8.0,1.0,3.0,2.0,1.0,2.0,3.0,1.0,1.0,2.0,2.0,2.0,3.0,3.0,2.0,2.0,3.0,3.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,2.0,8.0,2.0,8.0,1.0,9.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,2.0,8.0,2.0,2.0,8.0,8.0,3.0,2.0,2.0,8.0,9.0,8.0,1.0,8.0,1.0,2.0,1.0,8.0,3.0,2.0,NaN
18,2.0,1.0,1.0,3.0,4.0,2.0,2.0,2.0,3.0,2.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,2.0,4.0,3.0,1.0,2.0,2.0,3.0,2.0,1.0,2.0,3.0,1.0,4.0,2.0,2.0,4.0,3.0,4.0,2.0,4.0,2.0,2.0,4.0,4.0,2.0,4.0,4.0,2.0,5.0,3.0,2.0,1.0,4.0,3.0,3.0,3.0,2.0,3.0,4.0,2.0,3.0,2.0,4.0,2.0,4.0,2.0,3.0,2.0,4.0,3.0,3.0,4.0,3.0,2.0,2.0,2.0,...,1.0,4.0,3.0,2.0,2.0,2.0,8.0,4.0,3.0,1.0,3.0,4.0,1.0,3.0,3.0,2.0,9.0,3.0,1.0,4.0,3.0,3.0,4.0,3.0,4.0,3.0,3.0,4.0,4.0,3.0,5.0,3.0,2.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0,3.0,3.0,1.0,8.0,3.0,2.0,3.0,8.0,8.0,3.0,1.0,3.0,1.0,1.0,2.0,8.0,5.0,2.0,3.0,3.0,8.0,2.0,3.0,1.0,2.0,2.0,3.0,3.0,3.0,4.0,NaN
19,3.0,2.0,3.0,2.0,2.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,3.0,1.0,2.0,1.0,3.0,3.0,2.0,3.0,1.0,1.0,2.0,2.0,2.0,3.0,3.0,4.0,2.0,3.0,2.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,3.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,1.0,3.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,1.0,2.0,1.0,1.0,1.0,...,1.0,1.0,3.0,2.0,3.0,2.0,8.0,3.0,3.0,3.0,8.0,3.0,1.0,1.0,3.0,1.0,9.0,8.0,2.0,2.0,2.0,2.0,3.0,2.0,4.0,3.0,3.0,3.0,3.0,1.0,3.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,3.0,2.0,3.0,9.0,8.0,8.0,3.0,2.0,3.0,2.0,3.0,3.0,8.0,NaN
20,2.0,2.0,2.0,1.0,2.0,3.0,3.0,3.0,3.0,1.0,3.0,3.0,3.0,4.0,3.0,3.0,3.0,1.0,3.0,3.0,1.0,2.0,3.0,3.0,3.0,2.0,3.0,1.0,2.0,3.0,2.0,2.0,3.0,2.0,3.0,2.0,3.0,2.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,3.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,1.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,1.0,1.0,1.0,...,2.0,2.0,3.0,2.0,8.0,2.0,8.0,2.0,3.0,3.0,1.0,3.0,2.0,3.0,3.0,8.0,9.0,8.0,1.0,2.0,3.0,3.0,4.0,9.0,2.0,3.0,3.0,4.0,3.0,2.0,4.0,2.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,3.0,8.0,3.0,8.0,2.0,3.0,8.0,3.0,2.0,8.0,8.0,8.0,2.0,2.0,8.0,3.0,2.0,2.0,3.0,2.0,3.0,2.0,3.0,9.0,8.0,8.0,3.0,2.0,3.0,2.0,3.0,3.0,8.0,NaN
21,1.0,2.0,2.0,1.0,1.0,1.0,3.0,3.0,2.0,1.0,3.0,3.0,3.0,4.0,8.0,3.0,3.0,3.0,3.0,3.0,4.0,2.0,3.0,1.0,2.0,8.0,3.0,3.0,1.0,2.0,2.0,1.0,4.0,2.0,3.0,2.0,3.0,2.0,2.0,3.0,3.0,1.0,4.0,3.0,2.0,4.0,2.0,3.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,...,8.0,2.0,8.0,1.0,8.0,2.0,8.0,3.0,3.0,2.0,2.0,3.0,2.0,3.0,3.0,1.0,9.0,8.0,2.0,2.0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,3.0,2.0,1.0,2.0,2.0,3.0,1.0,8.0,8.0,1.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,2.0,2.0,8.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,9.0,8.0,8.0,3.0,3.0,3.0,3.0,3.0,3.0,8.0,NaN
22,3.0,3.0,3.0,3.0,3.0,4.0,3.0,3.0,8.0,3.0,3.0,4.0,3.0,4.0,3.0,3.0,3.0,3.0,4.0,3.0,8.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,4.0,1.0,3.0,2.0,2.0,4.0,3.0,1.0,3.0,3.0,2.0,4.0,2.0,3.0,1.0,2.0,2.0,2.0,2.0,4.0,3.0,3.0,2.0,3.0,4.0,2.0,3.0,4.0,3.0,4.0,3.0,3.0,4.0,3.0,3.0,3.0,1.0,1.0,1.0,...,3.0,2.0,4.0,2.0,8.0,2.0,8.0,4.0,4.0,1.0,4.0,4.0,1.0,4.0,4.0,3.0,9.0,8.0,2.0,3.0,3.0,4.0,4.0,3.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,3.0,3.0,3.0,8.0,3.0,3.0,8.0,3.0,8.0,2.0,1.0,1.0,2.0,3.0,3.0,3.0,1.0,2.0,3.0,1.0,3.0,1.0,3.0,2.0,1.0,1.0,1.0,3.0,3.0,3.0,9.0,8.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,8.0,NaN
23,1.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,4.0,8.0,3.0,4.0,3.0,3.0,3.0,4.0,2.0,3.0,2.0,3.0,1.0,3.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,4.0,3.0,3.0,2.0,4.0,2.0,1.0,3.0,3.0,1.0,3.0,3.0,1.0,4.0,2.0,2.0,1.0,2.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,1.0,1.0,1.0,...,3.0,1.0,4.0,1.0,8.0,1.0,8.0,4.0,4.0,3.0,3.0,4.0,3.0,3.0,4.0,8.0,9.0,8.0,2.0,2.0,3.0,3.0,3.0,4.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,3.0,1.0,1.0,3.0,8.0,3.0,3.0,8.0,3.0,8.0,3.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,1.0,2.0,2.0,2.0,2.0,8.0,1.0,3.0,3.0,3.0,3.0,9.0,8.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,8.0,NaN
24,2.0,3.0,1.0,2.0,1.0,2.0,1.0,1.0,3.0,2.0,3.0,4.0,3.0,3.0,3.0,4.0,3.0,3.0,4.0,2.0,1.0,2.0,3.0,1.0,1.0,3.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0,4.0,2.0,4.0,2.0,2.0,2.0,3.0,1.0,3.0,3.0,3.0,4.0,2.0,3.0,1.0,2.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,2.0,8.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,...,2.0,8.0,3.0,2.0,8.0,1.0,8.0,4.0,1.0,3.0,3.0,3.0,2.0,3.0,3.0,8.0,9.0,8.0,2.0,3.0,3.0,3.0,4.0,8.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,1.0,1.0,1.0,8.0,1.0,1.0,1.0,1.0,8.0,8.0,8.0,3.0,3.0,8.0,3.0,3.0,3.0,8.0,8.0,3.0,2.0,3.0,2.0,2.0,2.0,3.0,3.0,2.0,2.0,3.0,9.0,8.0,9.0,3.0,3.0,3.0,3.0,3.0,3.0,8.0,NaN
25,3.0,3.0,2.0,2.0,1.0,3.0,3.0,2.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,3.0,3.0,4.0,2.0,2.0,8.0,2.0,4.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,2.0,2.0,3.0,3.0,4.0,1.0,3.0,2.0,2.0,3.0,3.0,1.0,3.0,3.0,2.0,3.0,2.0,3.0,2.0,3.0,3.0,2.0,3.0,3.0,4.0,1.0,2.0,3.0,8.0,3.0,8.0,3.0,8.0,3.0,8.0,2.0,3.0,2.0,8.0,3.0,1.0,1.0,1.0,...,1.0,8.0,8.0,8.0,8.0,2.0,8.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,8.0,9.0,8.0,2.0,3.0,2.0,4.0,4.0,9.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,3.0,3.0,3.0,3.0,8.0,3.0,3.0,8.0,3.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,3.0,8.0,3.0,2.0,8.0,2.0,3.0,3.0,3.0,3.0,9.0,8.0,9.0,3.0,3.0,3.0,3.0,3.0,3.0,8.0,NaN
26,3.0,3.0,1.0,2.0,2.0,2.0,3.0,1.0,2.0,1.0,3.0,3.0,8.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,8.0,2.0,2.0,1.0,2.0,3.0,2.0,2.0,3.0,3.0,2.0,2.0,3.0,3.0,3.0,1.0,3.0,2.0,1.0,3.0,2.0,1.0,3.0,3.0,2.0,3.0,2.0,3.0,1.0,2.0,2.0,3.0,2.0,2.0,1.0,2.0,2.0,1.0,3.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,1.0,1.0,1.0,...,8.0,8.0,3.0,2.0,8.0,2.0,8.0,2.0,3.0,3.0,3.0,3.0,2.0,3.0,2.0,8.0,9.0,8.0,2.0,3.0,2.0,3.0,3.0,8.0,3.0,3.0,3.0,2.0,3.0,4.0,3.0,2.0,3.0,1.0,2.0,8.0,3.0,8.0,8.0,3.0,8.0,8.0,3.0,8.0,8.0,8.0,3.0,8.0,3.0,8.0,8.0,8.0,2.0,8.0,2.0,2.0,8.0,2.0,8.0,2.0,2.0,3.0,9.0,8.0,9.0,3.0,3.0,3.0,3.0,3.0,3.0,8.0,NaN
27,4.0,3.0,4.0,3.0,3.0,3.0,3.0,3.0,2.0,4.0,3.0,2.0,8.0,8.0,3.0,3.0,3.0,1.0,2.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,4.0,2.0,3.0,2.0,2.0,3.0,2.0,1.0,3.0,3.0,2.0,4.0,2.0,2.0,1.0,2.0,2.0,2.0,3.0,3.0,2.0,3.0,2.0,8.0,9.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,3.0,1.0,1.0,1.0,...,4.0,8.0,3.0,8.0,8.0,2.0,8.0,1.0,3.0,3.0,3.0,3.0,2.0,3.0,3.0,8.0,9.0,8.0,2.0,3.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,1.0,2.0,3.0,8.0,3.0,3.0,8.0,3.0,8.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,3.0,8.0,3.0,8.0,2.0,2.0,1.0,3.0,3.0,3.0,3.0,3.0,9.0,8.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,8.0,NaN
28,4.0,2.0,4.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0,1.0,4.0,5.0,4.0,4.0,4.0,5.0,4.0,4.0,3.0,4.0,4.0,4.0,3.0,8.0,8.0,8.0,3.0,3.0,3.0,4.0,3.0,4.0,2.0,4.0,8.0,3.0,4.0,3.0,3.0,4.0,4.0,3.0,4.0,3.0,3.0,2.0,4.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,4.0,4.0,4.0,5.0,4.0,4.0,4.0,3.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,4.0,4.0,3.0,2.0,1.0,4.0,1.0,3.0,1.0,4.0,4.0,3.0,3.0,4.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,2.0,2.0,3.0,8.0,1.0,1.0,1.0,8.0,1.0,3.0,2.0,2.0,4.0,8.0,8.0,8.0,8.0,8.0,8.0,1.0,1.0,1.0,1.0,2.0,1.0,8.0,1.0,4.0,1.0,3.0,1.0,4.0,1.0,2.0,2.0,3.0,8.0,8.0,1.0,4.0,NaN
29,2.0,2.0,2.0,2.0,2.0,1.0,2.0,3.0,2.0,1.0,3.0,3.0,2.0,1.0,2.0,3.0,2.0,3.0,1.0,3.0,2.0,1.0,2.0,3.0,1.0,2.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,8.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,...,1.0,2.0,1.0,2.0,2.0,2.0,8.0,1.0,2.0,3.0,2.0,2.0,2.0,3.0,2.0,2.0,8.0,8.0,8.0,2.0,2.0,2.0,2.0,8.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,8.0,1.0,2.0,2.0,2.0,8.0,2.0,2.0,8.0,2.0,8.0,8.0,2.0,2.0,2.0,8.0,2.0,8.0,2.0,1.0,1.0,2.0,3.0,2.0,2.0,8.0,2.0,3.0,2.0,8.0,2.0,8.0,8.0,3.0,8.0,8.0,3.0,NaN
30,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0,4.0,3.0,4.0,4.0,4.0,3.0,4.0,3.0,4.0,3.0,4.0,3.0,3.0,3.0,3.0,4.0,4.0,3.0,2.0,2.0,4.0,4.0,4.0,2.0,4.0,3.0,3.0,3.0,3.0,3.0,4.0,3.0,4.0,3.0,3.0,4.0,2.0,3.0,4.0,3.0,4.0,4.0,4.0,2.0,4.0,3.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,4.0,4.0,3.0,4.0,...,2.0,2.0,4.0,3.0,3.0,3.0,8.0,4.0,4.0,2.0,3.0,4.0,3.0,3.0,3.0,3.0,8.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,3.0,4.0,4.0,4.0,3.0,8.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,1.0,4.0,3.0,4.0,3.0,4.0,2.0,4.0,4.0,8.0,2.0,8.0,2.0,2.0,8.0,8.0,2.0,NaN