In [1]:
import numpy as np
import pandas as pd
import psycopg
from sqlalchemy import create_engine 
import dotenv
import os

In [2]:
dotenv.load_dotenv()

False

In [3]:
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")

In [5]:
games = pd.read_csv("data/games.csv")
teams = pd.read_csv("data/teams.csv")
players = pd.read_csv("data/players.csv")
team_game = pd.read_csv("data/team_game.csv")
player_game = pd.read_csv("data/player_game.csv")

#### Step 1: Connect to our Postgres Server (running via Docker), Create an empty NBA database

In [7]:
dbserver = psycopg.connect(
    host="localhost",
    port=5432,
    dbname="postgres",
    user="postgres",
    password=POSTGRES_PASSWORD
)

dbserver.autocommit = True

In [8]:
cursor = dbserver.cursor()

In [12]:
try:
    cursor.execute("CREATE DATABASE nba;")
except:
    cursor.execute("DROP DATABASE nba;")
    cursor.execute("CREATE DATABASE nba;")

#### Step 2: Put our data into that database

First we will create a SQL Alchemy engine -- a shortcut to the NBA database we just made

In [15]:
dbms = "postgresql"
package = "psycopg"
user = "postgres"
password = POSTGRES_PASSWORD
host = "localhost"
port = 5432
database = "nba"

engine = create_engine(f"{dbms}+{package}://{user}:{password}@{host}:{port}/{database}")

In [16]:
games.to_sql("games", con=engine, index=False, chunksize=1000, if_exists="replace")
players.to_sql("players", con=engine, index=False, chunksize=1000, if_exists="replace")
teams.to_sql("teams", con=engine, index=False, chunksize=1000, if_exists="replace")
player_game.to_sql("player_game", con=engine, index=False, chunksize=1000, if_exists="replace")
team_game.to_sql("team_game", con=engine, index=False, chunksize=1000, if_exists="replace")

-3

#### Step 2: SQL it like crazy

In [19]:
myquery = """
SELECT *
FROM games
WHERE home_team_id = 18

"""

pd.read_sql_query(myquery, con=engine)

        game_id   game_date  home_team_id  away_team_id     season_type
0   401809234.0  2025-10-22          18.0           5.0  Regular Season
1   401809238.0  2025-12-25          18.0           5.0  Regular Season
2   401809249.0  2026-01-19          18.0           6.0  Regular Season
3   401809781.0  2025-11-14          18.0          14.0  Regular Season
4   401809816.0  2025-11-28          18.0          15.0  Regular Season
5   401809839.0  2025-12-16          18.0          24.0  Regular Season
6   401809945.0  2025-10-24          18.0           2.0  Regular Season
7   401810008.0  2025-11-02          18.0           4.0  Regular Season
8   401810014.0  2025-11-03          18.0          27.0  Regular Season
9   401810030.0  2025-11-05          18.0          16.0  Regular Season
10  401810047.0  2025-11-09          18.0          17.0  Regular Season
11  401810063.0  2025-11-11          18.0          29.0  Regular Season
12  401810070.0  2025-11-12          18.0          19.0  Regular Season
13  401810158.0  2025-11-30          18.0          28.0  Regular Season
14  401810183.0  2025-12-03          18.0          30.0  Regular Season
15  401810198.0  2025-12-05          18.0          26.0  Regular Season
16  401810212.0  2025-12-07          18.0          19.0  Regular Season
17  401810237.0  2025-12-19          18.0          20.0  Regular Season
18  401810253.0  2025-12-21          18.0          14.0  Regular Season
19  401810334.0  2026-01-02          18.0           1.0  Regular Season
20  401810342.0  2026-01-03          18.0          20.0  Regular Season
21  401810377.0  2026-01-07          18.0          12.0  Regular Season
22  401810451.0  2026-01-17          18.0          21.0  Regular Season
23  401810477.0  2026-01-21          18.0          17.0  Regular Season
24  401810520.0  2026-01-27          18.0          23.0  Regular Season
25  401810545.0  2026-01-30          18.0          22.0  Regular Season
26  401810563.0  2026-02-01          18.0          13.0  Regular Season
27  401810581.0  2026-02-04          18.0           7.0  Regular Season
28  401810626.0  2026-02-10          18.0          11.0  Regular Season
29  401810651.0  2026-02-19          18.0           8.0  Regular Season
30  401810671.0  2026-02-21          18.0          10.0  Regular Season
31  401810723.0  2026-03-01          18.0          24.0  Regular Season
32  401810748.0  2026-03-04          18.0          25.0  Regular Season
33  401810836.0  2026-03-15          18.0           9.0  Regular Season
34  401810849.0  2026-03-17          18.0          11.0  Regular Season
35  401810889.0  2026-03-22          18.0          27.0  Regular Season
36  401810903.0  2026-03-24          18.0           3.0  Regular Season
37  401810978.0  2026-04-03          18.0           4.0  Regular Season
38  401811023.0  2026-04-09          18.0           2.0  Regular Season
39  401811031.0  2026-04-10          18.0          28.0  Regular Season
40  401811045.0  2026-04-12          18.0          30.0  Regular Season
41  401859965.0  2026-06-08          18.0          24.0        Playoffs
42  401859966.0  2026-06-10          18.0          24.0        Playoffs
43  401869189.0  2026-04-18          18.0           1.0        Playoffs
44  401869387.0  2026-04-20          18.0           1.0        Playoffs
45  401869392.0  2026-04-28          18.0           1.0        Playoffs
46  401871159.0  2026-05-04          18.0          20.0        Playoffs
47  401871160.0  2026-05-06          18.0          20.0        Playoffs
48  401873341.0  2026-05-19          18.0           5.0        Playoffs
49  401873342.0  2026-05-21          18.0           5.0        Playoffs

In [ ]:
# All player that score 50

In [27]:
myquery = """
SELECT pg.player_id,
    SUM(pg.pts + pg.fg3m - pg.fga + 2 * pg.fgm - pg.fta + pg.ftm + pg.oreb + pg.dreb + 2 * pg.ast + 4 * pg.stl + 4 * pg.blk - 2 * pg.tov) AS mvp_score
FROM player_game pg
INNER JOIN games g
    ON pg.game_id = g.game_id
INNER JOIN players p
    ON pg.player_id = p.player_id
WHERE g.season_type = 'Regular Season'
GROUP BY pg.player_id, p.player_name
ORDER BY mvp_score DESC
"""

pd.read_sql_query(myquery, con=engine)

     player_id  mvp_score
0    3112335.0     4310.0
1    3945274.0     3785.0
2    4278073.0     3773.0
3    4431678.0     3652.0
4    5104157.0     3579.0
..         ...        ...
577  5242496.0        1.0
578  4702785.0        1.0
579  4597865.0        1.0
580  4590360.0        1.0
581  4397450.0        0.0

[582 rows x 2 columns]